export const queryKeys = {
  authMe: ['auth', 'me'] as const,
  newReportBootstrap: (userId?: string | null) => ['bootstrap', 'new-report', { userId: userId || 'anonymous' }] as const,
  reportDetailBootstrap: (reportId: string, userId?: string | null) => ['bootstrap', 'report-detail', reportId, { userId: userId || 'anonymous' }] as const,
  gestorBootstrap: (userId?: string | null) => ['bootstrap', 'gestor', { userId: userId || 'anonymous' }] as const,
  collaborators: ['collaborators'] as const,
  projects: (active?: boolean, userId?: string | null) => ['projects', { active, userId: userId || 'anonymous' }] as const,
  equipment: ['equipment'] as const,
  inhibitionOptions: ['inhibition-options'] as const,
  units: ['units'] as const,
  unitCategories: ['units', 'categories'] as const,
  manometers: ['manometers'] as const,
  counters: ['particle-counters'] as const,
  equipamentos: (categoryId?: string | null) => ['equipamentos', 'items', { categoryId: categoryId || 'all' }] as const,
  equipamentoCategories: ['equipamentos', 'categories'] as const,
  drafts: (userId?: string | null) => ['drafts', { userId: userId || 'anonymous' }] as const,
  users: (group?: 'internal' | 'client') => ['users', { group }] as const,
  surveys: ['surveys'] as const,
  surveyQuestions: ['surveys', 'questions'] as const,
  reports: (filters?: unknown, userId?: string | null) => ['reports', filters ?? {}, { userId: userId || 'anonymous' }] as const,
  reportPage: (filters?: unknown, userId?: string | null) => ['reports', 'page', filters ?? {}, { userId: userId || 'anonymous' }] as const,
  reportCounts: (queries?: unknown, userId?: string | null) => ['reports', 'counts', queries ?? [], { userId: userId || 'anonymous' }] as const,
  reportAudit: (reportId: string) => ['reports', reportId, 'audit'] as const
};
