CREATE TABLE IF NOT EXISTS "RomaneioCatalogSyncState" (
  "id" TEXT NOT NULL,
  "sourceHash" TEXT NOT NULL,
  "syncedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "RomaneioCatalogSyncState_pkey" PRIMARY KEY ("id")
);
