import { validationFixture as f } from './redesign-audit-support';

export interface AuditView { label: string; path: string; role?: string; preview?: boolean; open?: string; openExact?: boolean; loading?: boolean; expectedLoadError?: boolean }
const sections = (module: string, key: string, values: string[]): AuditView[] => values.map(value => ({label:`${module} / ${value}`,path:`/${module}?${key}=${value}`}));
export const pageInventory: AuditView[] = [
  ...['modulos','conta','operacoes','admin/accounts'].map(path=>({label:path,path:`/${path}`})),
  ...sections('admin/tokens','etapa',['credenciais','configurar','playground']),
  ...sections('rdo/gestor','tab',['pendentes','aprovados','projetos','arquivados','equipe','usuarios','nps','estatisticas']),
  {label:'RDO / detalhe',path:`/rdo/gestor/relatorio/${f.reportId}`},
  {label:'RDO / novo',path:'/rdo/relatorio/novo'},
  ...sections('manutencao-producao','tab',['manutencao','producao','programacao-manutencao','historico-manutencao']),
  {label:'Manutenção / novo relatório',path:'/manutencao-producao/relatorio/novo?tipo=manutencao'},
  {label:'Produção / novo relatório',path:'/manutencao-producao/relatorio/novo?tipo=producao'},
  ...sections('equipamentos','tab',['dashboard','categories','config','maintenance','notifications']),
  ...sections('estoque','tab',['resumo','movimentacoes','itens','categorias']),
  ...sections('qualidade','tab',['registros','naturezas']),
  {label:'Qualidade / formulário',path:'/qualidade',open:'Registrar'},
  ...sections('epi','tab',['collaborators','catalog']),
  {label:'EPI / ficha',path:'/epi',open:'Colaborador Validação',openExact:false},
  ...sections('romaneio','tab',['romaneios','equipamentos','notificacoes']),
  {label:'Romaneio / novo',path:'/romaneio/novo'},
  ...(f.romaneioId?[{label:'Romaneio / edição',path:`/romaneio/novo?edit=${f.romaneioId}`}]:[]),
  ...sections('acompanhamento','section',['dashboard','projetos','sede','custo']),
  ...['ponto','auditoria','rates','categorias','simulador'].map(cost=>({label:`Acompanhamento / custo / ${cost}`,path:`/acompanhamento?section=custo&cost=${cost}`})),
  {label:'Acompanhamento / projeto',path:`/acompanhamento?section=projetos&project=${f.project.id}`},
  ...sections('efetivo','section',['visao-geral','calendario','colaboradores','disponibilidade','evolucao','produtividade','administracao']),
  ...['feriados','notificacoes','atividade'].map(adminTab=>({label:`Efetivo / administração / ${adminTab}`,path:`/efetivo?section=administracao&adminTab=${adminTab}`})),
  {label:'Efetivo / disponibilidade em calendário',path:'/efetivo?section=disponibilidade&disponibilidadeView=calendar'},
  ...['day','week'].map(view=>({label:`Efetivo / calendário / ${view}`,path:`/efetivo?section=calendario&view=${view}`})),
  {label:'Efetivo / colaboradores / ficha',path:`/efetivo?section=colaboradores&colaborador=${f.collaborator.id}`},
  {label:'Efetivo / evolução / planejamento',path:`/efetivo?section=evolucao&projeto=${f.project.id}`},
  ...sections('assinaturas','tab',['active','archived']),
  {label:'Assinaturas / novo documento',path:'/assinaturas',open:'Novo documento'},
  ...(f.signatureDraftId?['setup','audit'].map(tab=>({label:`Assinaturas / rascunho / ${tab}`,path:`/assinaturas?doc=${f.signatureDraftId}&tab=${tab}`})):[]),
  ...(f.signaturePublishedId?['details','audit'].map(tab=>({label:`Assinaturas / publicado / ${tab}`,path:`/assinaturas?doc=${f.signaturePublishedId}&tab=${tab}`})):[]),
  {label:'Privacidade / solicitações',path:'/privacidade/solicitacoes'},
  ...['/rdo/home','/rdo/andamento','/rdo/meus-relatorios','/rdo/meus-relatorios/arquivados','/rdo/relatorio/novo'].map(path=>({label:`Colaborador / ${path}`,path,role:'collaborator'})),
  {label:'Coordenador / relatórios',path:'/rdo/coordenador',role:'viewer'},
  {label:'Coordenador / detalhe',path:`/rdo/coordenador/relatorio/${f.reportId}`,role:'viewer'},
  {label:'Cliente / relatórios',path:'/rdo/cliente',role:'client'},
  ...[
    ['/login','Login'],['/forgot-password','Recuperar senha'],['/reset-password','Redefinir senha / token ausente'],
    ['/privacidade','Política de privacidade'],['/privacidade/direitos','Direitos do titular'],
    ['/confirmar-email?visualizar=1','Confirmação de e-mail / demonstração'],
    ['/notificacoes/exemplo?visualizar=1','Preferências / demonstração'],['/pesquisa/exemplo?visualizar=1','Pesquisa / demonstração'],
    ['/assinar/exemplo?visualizar=1','Assinatura RDO / demonstração'],
    ['/validar-assinatura/invalido','Validação RDO / código inválido'],
    ['/visualizar','Galeria de demonstrações'],['/visualizar/carregamento','Animações de carregamento'],
    ['/visualizar/operacoes','Operações / demonstração'],['/visualizar/documentos','Documentos / demonstração']
  ].map(([path,label])=>({label,path,role:'public',preview:path.includes('visualizar'),loading:path==='/visualizar/carregamento'})),
  {label:'Validação avulsa / código inválido',path:'/validar-documento/invalido',role:'public',expectedLoadError:true},
  ...(f.epiPublicToken?[{label:'EPI / assinatura pública',path:`/epi/assinar/${f.epiPublicToken}`,role:'public'}]:[]),
  ...(f.signaturePublicPath?[{label:'Assinatura avulsa / convite',path:f.signaturePublicPath,role:'public'}]:[]),
  ...['Adicionar documento','Editar documento','Adicionar versão','Registrar aceite','Encerrar projeto antigo','Checklist de contato'].map(open=>({label:`Efetivo / diálogo / ${open}`,path:'/visualizar/documentos',role:'public',preview:true,open}))
];
