import { expect, test, type Page } from '@playwright/test';

const panelFor = (page: Page) => page.getByRole('region', { name: 'Metas semanais de avanço', exact: true });

test.beforeEach(async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-10-01T12:00:00Z'));
  await page.goto('/test/browser/weekly-progress.html');
  await panelFor(page).getByRole('button', { name: 'Definir meta', exact: true }).click();
});

test('muda automaticamente de 300 m com um serviço para 100 m de limpeza e 100 m de teste', async ({ page }) => {
  const panel = panelFor(page);
  await panel.getByLabel('Medida da meta').selectOption('M');
  const first = panel.locator('.mission-weekly-scenario').nth(0);
  await first.getByLabel('Nome do cenário').fill('Um tipo de serviço');
  await first.getByLabel('Quando aplicar').selectOption('SERVICE_COUNT');
  await first.getByLabel('Quantidade de tipos de serviço').fill('1');
  await first.getByLabel('Total geral (m)').fill('300');
  await panel.getByRole('button', { name: 'Adicionar cenário', exact: true }).click();
  const pair = panel.locator('.mission-weekly-scenario').nth(1);
  await pair.getByLabel('Nome do cenário').fill('Limpeza + teste');
  // Selecionar a distribuição antes dos serviços também precisa funcionar.
  await pair.getByLabel('Distribuição da meta').selectOption('SERVICE');
  await pair.getByLabel('Limpeza química', { exact: true }).check();
  await pair.getByLabel('Teste de pressão', { exact: true }).check();
  await pair.getByLabel('Limpeza química (m)').fill('100');
  await pair.getByLabel('Teste de pressão (m)').fill('100');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  const current = panel.locator('.mission-weekly-progress-current');
  await expect(current).toContainText('Cenário: Limpeza + teste');
  await expect(current.locator('.mission-weekly-status')).toHaveText('Abaixo da meta');
  await expect(current.locator('dd').nth(0)).toHaveText('200 m');
  await expect(current.locator('dd').nth(1)).toHaveText('200 m');
  await expect(page.locator('[data-acp-weekly-current]')).toContainText('50% da meta por serviço');
  await page.getByRole('button', { name: 'Usar somente limpeza', exact: true }).click();
  await expect(current).toContainText('Cenário: Um tipo de serviço');
  await expect(current.locator('dd').nth(0)).toHaveText('300 m');
  await page.getByRole('button', { name: 'Trocar área', exact: true }).click();
  await expect(current).toContainText('Cenário: Um tipo de serviço');
  await panel.getByRole('button', { name: 'Definir meta', exact: true }).click();
  await expect(panel.getByLabel('Medida da meta')).toHaveValue('M');
  await expect(panel.locator('.mission-weekly-scenario')).toHaveCount(2);
});

test('cadastra somente a taxa e recalcula a meta pelos RDOs sem criar uma revisão', async ({ page }) => {
  const panel = panelFor(page);
  await page.getByRole('button', { name: 'Usar filtragem', exact: true }).click();
  await panel.getByLabel('Medida da meta').selectOption('L');
  await panel.getByLabel('Base de cálculo').selectOption('PER_PRODUCTIVE_DAY');
  await panel.getByLabel('Distribuição da meta').selectOption('SERVICE');
  await panel.getByLabel('Tipo de serviço').selectOption('FILTRAGEM');
  await panel.getByLabel('Filtragem (L/colaborador produtivo/dia)').fill('1000');
  await expect(panel.getByLabel('Colaboradores produtivos')).toHaveCount(0);
  await expect(panel.getByLabel('Dias produtivos na semana')).toHaveCount(0);
  await expect(panel.getByLabel('Horas de um dia produtivo')).toHaveValue('8');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  const current = panel.locator('.mission-weekly-progress-current');
  await expect(current.locator('dd').nth(0)).toHaveText('10.000 L');
  await expect(current).toContainText('1.200 L/colaborador produtivo/dia');
  await expect(current.locator('.mission-weekly-status')).toHaveText('Acima da meta');
  await expect(current).toContainText('80 horas de colaboradores = 10 colaborador-dias');
  await page.getByRole('button', { name: 'Atualizar tempo produtivo do RDO', exact: true }).click();
  await expect(current.locator('dd').nth(0)).toHaveText('15.000 L');
  await expect(panel.getByText('2 versões', { exact: true })).toHaveCount(0);
  await expect(current.locator('.mission-weekly-status')).toHaveText('Abaixo da meta');
  await panel.getByRole('button', { name: 'Definir meta', exact: true }).click();
  await expect(panel.getByLabel('Filtragem (L/colaborador produtivo/dia)')).toHaveValue('1000');
  await panel.getByLabel('Filtragem (L/colaborador produtivo/dia)').fill('1100');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await expect(current.locator('dd').nth(0)).toHaveText('16.500 L');
  await panel.getByText('2 versões', { exact: true }).click();
  await expect(panel.locator('.mission-weekly-progress-table details')).toContainText('1.000 L/colaborador produtivo/dia');
  await expect(panel.locator('.mission-weekly-progress-table details')).toContainText('1.100 L/colaborador produtivo/dia');
  await page.getByRole('button', { name: 'Remover base produtiva do RDO', exact: true }).click();
  await expect(current.locator('.mission-weekly-status')).toHaveText('Sem dados suficientes');
  await expect(current.locator('dd').nth(0)).toHaveText('—');
  await expect(current.locator('dd').nth(1)).toHaveText('12.000 L');
  await expect(current).toContainText('falta RDO com equipe e horários desse serviço');
  await page.getByRole('button', { name: 'Alternar permissão', exact: true }).click();
  await expect(panel.getByRole('button', { name: 'Definir meta', exact: true })).toHaveCount(0);
});

test('selecionar filtragem exibe e salva volume em litros sem exigir a troca manual da medida', async ({ page }) => {
  const panel = panelFor(page);
  await page.getByRole('button', { name: 'Usar filtragem', exact: true }).click();
  await panel.getByLabel('Medida da meta').selectOption('M');
  await panel.getByLabel('Distribuição da meta').selectOption('SERVICE');
  await panel.getByLabel('Tipo de serviço').selectOption('FILTRAGEM');
  await expect(panel.getByLabel('Medida da meta')).toHaveValue('L');
  await expect(panel.getByLabel('Filtragem (m)')).toHaveCount(0);
  await panel.getByLabel('Filtragem (L)').fill('1000');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  const current = panel.locator('.mission-weekly-progress-current');
  await expect(current.locator('dd').nth(0)).toHaveText('1.000 L');
  await expect(current.locator('dd').nth(1)).toHaveText('12.000 L');
  await expect(current).toContainText('12.000 L de 1.000 L');
  await panel.getByRole('button', { name: 'Definir meta', exact: true }).click();
  await expect(panel.getByLabel('Medida da meta')).toHaveValue('L');
  await expect(panel.getByLabel('Filtragem (L)')).toHaveValue('1000');
});

test('cenário com limpeza e filtragem exibe metros e litros por serviço, sem somar unidades diferentes', async ({ page }) => {
  const panel = panelFor(page);
  await panel.getByLabel('Medida da meta').selectOption('M');
  await panel.getByLabel('Distribuição da meta').selectOption('SERVICE');
  await panel.getByLabel('Limpeza química (m)').fill('100');
  await panel.getByRole('button', { name: 'Adicionar serviço', exact: true }).click();
  await panel.getByLabel('Tipo de serviço').nth(1).selectOption('FILTRAGEM');
  await panel.getByLabel('Filtragem (L)').fill('1000');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await page.getByRole('button', { name: 'Usar somente limpeza', exact: true }).click();
  const current = panel.locator('.mission-weekly-progress-current');
  await expect(current.locator('dd').nth(0)).toContainText('Limpeza química: 100 m');
  await expect(current.locator('dd').nth(0)).toContainText('Filtragem: 1.000 L');
  await expect(current.locator('dd').nth(0)).toContainText('Por serviço');
  await expect(current.locator('.mission-weekly-status')).toHaveText('Abaixo da meta');
  await expect(page.locator('[data-acp-weekly-current]')).toContainText('0% da meta');
  await expect(current.getByText('Filtragem', { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)).toBeLessThanOrEqual(1);
  await page.screenshot({ path: '../output/playwright/weekly-target-mixed-mobile.png', fullPage: true });
});

test('cadastro físico permanece utilizável no celular', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  const panel = panelFor(page);
  await panel.getByLabel('Medida da meta').selectOption('M');
  await panel.getByLabel('Base de cálculo').selectOption('PER_PRODUCTIVE_DAY');
  await panel.getByLabel('Total geral (m/colaborador produtivo/dia)').fill('42');
  await expect(panel.getByLabel('Horas de um dia produtivo')).toHaveValue('8');
  await expect(panel.getByText('Equipe e tempo produtivo vêm automaticamente dos RDOs, por serviço.', { exact: false })).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)).toBeLessThanOrEqual(1);
  await page.screenshot({ path: '../output/playwright/weekly-target-rate-mobile.png', fullPage: true });
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await expect(panel.locator('.mission-weekly-progress-current dd').nth(0)).toHaveText('630 m');
  await expect.poll(() => panel.locator('.mission-weekly-progress-table').evaluate(element => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(1);
});

test('preenche jornada semanal do projeto, permite edição e preserva a jornada salva nas duas áreas', async ({ page }) => {
  await page.goto('/test/browser/weekly-progress.html?workdayHours=09:30&weekendWorkdayHours=04:00');
  const panel = panelFor(page);
  await panel.getByRole('button', { name: 'Definir meta', exact: true }).click();
  await page.getByRole('button', { name: 'Usar filtragem', exact: true }).click();
  await panel.getByLabel('Medida da meta').selectOption('L');
  await panel.getByLabel('Base de cálculo').selectOption('PER_PRODUCTIVE_DAY');
  const reference = panel.getByLabel('Horas de um dia produtivo');
  await expect(reference).toHaveValue('9.5');
  await reference.fill('7.5');
  await panel.getByLabel('Total geral (L/colaborador produtivo/dia)').fill('1000');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await expect(panel.locator('.mission-weekly-progress-current dd').nth(0)).toHaveText('10.666,67 L');
  await page.getByRole('button', { name: 'Trocar área', exact: true }).click();
  await panel.getByRole('button', { name: 'Definir meta', exact: true }).click();
  await expect(reference).toHaveValue('7.5');
  await panel.getByRole('button', { name: 'Cancelar', exact: true }).click();
  await panel.getByRole('button', { name: 'Definir meta', exact: true }).click();
  await panel.getByLabel(/^Semana\s*\*?$/).fill('2026-10-05');
  await panel.getByLabel('Medida da meta').selectOption('M');
  await panel.getByLabel('Base de cálculo').selectOption('PER_PRODUCTIVE_DAY');
  await expect(reference).toHaveValue('7.5');
  await panel.getByRole('button', { name: 'Cancelar', exact: true }).click();
  await panel.getByRole('button', { name: 'Definir meta da semana de 21/09/2026', exact: true }).click();
  await panel.getByLabel('Medida da meta').selectOption('M');
  await panel.getByLabel('Base de cálculo').selectOption('PER_PRODUCTIVE_DAY');
  await expect(reference).toHaveValue('9.5');
});

test('alterar o dia ou a semana preserva cenários, taxas e jornada, inclusive alterações ainda não salvas', async ({ page }) => {
  const panel = panelFor(page);
  await panel.getByLabel('Medida da meta').selectOption('M');
  await panel.getByLabel('Base de cálculo').selectOption('PER_PRODUCTIVE_DAY');
  await panel.getByLabel('Horas de um dia produtivo').fill('7.5');
  const first = panel.locator('.mission-weekly-scenario').nth(0);
  await first.getByLabel('Nome do cenário').fill('Um serviço');
  await first.getByLabel('Quando aplicar').selectOption('SERVICE_COUNT');
  await first.getByLabel('Total geral (m/colaborador produtivo/dia)').fill('42');
  await panel.getByRole('button', { name: 'Adicionar cenário', exact: true }).click();
  const pair = panel.locator('.mission-weekly-scenario').nth(1);
  await pair.getByLabel('Nome do cenário').fill('Limpeza + teste');
  await pair.getByLabel('Limpeza química', { exact: true }).check();
  await pair.getByLabel('Teste de pressão', { exact: true }).check();
  await pair.getByLabel('Distribuição da meta').selectOption('SERVICE');
  await pair.getByLabel('Limpeza química (m/colaborador produtivo/dia)').fill('100');
  await pair.getByLabel('Teste de pressão (m/colaborador produtivo/dia)').fill('80');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await panel.getByRole('button', { name: 'Definir meta', exact: true }).click();
  await panel.getByLabel('Horas de um dia produtivo').fill('6');
  await first.getByLabel('Total geral (m/colaborador produtivo/dia)').fill('45');
  await pair.getByLabel('Limpeza química (m/colaborador produtivo/dia)').fill('110');
  const week = panel.getByLabel(/^Semana\s*\*?$/);
  const preserved = async () => {
    await expect(panel.getByLabel('Medida da meta')).toHaveValue('M');
    await expect(panel.getByLabel('Base de cálculo')).toHaveValue('PER_PRODUCTIVE_DAY');
    await expect(panel.getByLabel('Horas de um dia produtivo')).toHaveValue('6');
    await expect(panel.locator('.mission-weekly-scenario')).toHaveCount(2);
    await expect(first.getByLabel('Nome do cenário')).toHaveValue('Um serviço');
    await expect(first.getByLabel('Quando aplicar')).toHaveValue('SERVICE_COUNT');
    await expect(first.getByLabel('Quantidade de tipos de serviço')).toHaveValue('1');
    await expect(first.getByLabel('Total geral (m/colaborador produtivo/dia)')).toHaveValue('45');
    await expect(pair.getByLabel('Nome do cenário')).toHaveValue('Limpeza + teste');
    await expect(pair.getByLabel('Limpeza química', { exact: true })).toBeChecked();
    await expect(pair.getByLabel('Teste de pressão', { exact: true })).toBeChecked();
    await expect(pair.getByLabel('Limpeza química (m/colaborador produtivo/dia)')).toHaveValue('110');
    await expect(pair.getByLabel('Teste de pressão (m/colaborador produtivo/dia)')).toHaveValue('80');
  };
  await week.fill('2026-10-01');
  await expect(week).toHaveValue('2026-09-28');
  await preserved();
  await week.fill('');
  await preserved();
  await week.fill('2026-10-08');
  await expect(week).toHaveValue('2026-10-05');
  await preserved();
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await expect(panel.getByRole('alert')).toHaveCount(0);
  await panel.getByRole('button', { name: 'Editar meta da semana de 05/10/2026', exact: true }).click();
  await preserved();
});

test('trocar para uma semana com meta conserva o formulário e salva uma nova revisão na semana escolhida', async ({ page }) => {
  const panel = panelFor(page);
  const week = panel.getByLabel(/^Semana\s*\*?$/);
  const planned = panel.getByLabel('Avanço previsto para a semana (p.p.)');
  await planned.fill('10');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await panel.getByRole('button', { name: 'Definir meta', exact: true }).click();
  await week.fill('2026-10-05');
  await planned.fill('15');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await panel.getByRole('button', { name: 'Editar meta da semana de 05/10/2026', exact: true }).click();
  await planned.fill('20');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await panel.getByRole('button', { name: 'Definir meta', exact: true }).click();
  await planned.fill('30');
  await week.fill('2026-10-08');
  await expect(planned).toHaveValue('30');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await expect(panel.getByRole('alert')).toHaveCount(0);
  const future = panel.getByRole('row').filter({ has: page.getByRole('button', { name: 'Editar meta da semana de 05/10/2026', exact: true }) });
  await expect(future.getByText('3 versões', { exact: true })).toBeVisible();
  await panel.getByRole('button', { name: 'Editar meta da semana de 05/10/2026', exact: true }).click();
  await expect(planned).toHaveValue('30');
});

test('preserva metas percentuais, semanas futuras e a recuperação de edição concorrente', async ({ page }) => {
  const panel = panelFor(page);
  await panel.getByLabel('Avanço previsto para a semana (p.p.)').fill('10');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  const current = panel.locator('.mission-weekly-progress-current');
  await expect(current.locator('.mission-weekly-status')).toHaveText('Dentro da meta');
  await page.getByRole('button', { name: 'Simular conflito na próxima gravação', exact: true }).click();
  await panel.getByRole('button', { name: 'Definir meta', exact: true }).click();
  await panel.getByLabel('Avanço previsto para a semana (p.p.)').fill('20');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await expect(panel.getByRole('alert')).toContainText('alterada por outra pessoa');
  await expect(panel.getByRole('button', { name: 'Salvar meta', exact: true })).toHaveCount(0);
  await expect(current.locator('dd').nth(0)).toHaveText('10 p.p.');
  await panel.getByRole('button', { name: 'Definir meta', exact: true }).click();
  await panel.getByLabel(/^Semana\s*\*?$/).fill('2026-10-05');
  await panel.getByLabel('Avanço previsto para a semana (p.p.)').fill('15');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await expect(panel.getByText('Semana futura', { exact: true })).toBeVisible();
  await expect(current.locator('dd').nth(0)).toHaveText('10 p.p.');
});

test('excluir exige confirmação, preserva histórico e permite recriar sem reativar versões antigas', async ({ page }) => {
  const panel = panelFor(page);
  const planned = () => panel.getByLabel('Avanço previsto para a semana (p.p.)');
  await planned().fill('10');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await panel.getByRole('button', { name: 'Definir meta', exact: true }).click();
  await planned().fill('15');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  const current = panel.locator('.mission-weekly-progress-current');
  const remove = () => panel.getByRole('button', { name: 'Excluir meta da semana de 28/09/2026', exact: true });
  await remove().click();
  const confirmation = page.getByRole('dialog', { name: 'Excluir meta semanal' });
  await expect(confirmation).toContainText('Semana de 28/09/2026');
  await confirmation.getByRole('button', { name: 'Cancelar', exact: true }).click();
  await expect(current.locator('dd').nth(0)).toHaveText('15 p.p.');
  await remove().click();
  await confirmation.getByRole('button', { name: 'Excluir meta', exact: true }).click();
  await expect(confirmation).toBeHidden();
  await expect(current.locator('.mission-weekly-status')).toHaveText('Sem meta definida');
  await expect(current.locator('dd').nth(0)).toHaveText('—');
  await expect(current.locator('dd').nth(1)).toHaveText('10 p.p.');
  await expect(remove()).toHaveCount(0);
  await panel.getByText('3 versões', { exact: true }).click();
  const history = panel.locator('.mission-weekly-progress-table details');
  await expect(history).toContainText('10 p.p.');
  await expect(history).toContainText('15 p.p.');
  await expect(history).toContainText('Meta excluída');
  await page.getByRole('button', { name: 'Trocar área', exact: true }).click();
  await expect(current.locator('.mission-weekly-status')).toHaveText('Sem meta definida');
  await expect(page.locator('[data-acp-weekly-current]')).toContainText('Sem meta');
  await panel.getByRole('button', { name: 'Definir meta', exact: true }).click();
  await planned().fill('0');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await expect(current.locator('dd').nth(0)).toHaveText('0 p.p.');
  await expect(panel.getByText('4 versões', { exact: true })).toBeVisible();
  await expect(remove()).toBeVisible();
  await page.getByRole('button', { name: 'Alternar permissão', exact: true }).click();
  await expect(panel.getByRole('button', { name: /Excluir meta da semana/ })).toHaveCount(0);
});

test('exclusão com conflito mantém a meta e exige uma nova confirmação', async ({ page }) => {
  const panel = panelFor(page);
  await panel.getByLabel('Avanço previsto para a semana (p.p.)').fill('10');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await page.getByRole('button', { name: 'Simular conflito na próxima gravação', exact: true }).click();
  await panel.getByRole('button', { name: 'Excluir meta da semana de 28/09/2026', exact: true }).click();
  const confirmation = page.getByRole('dialog', { name: 'Excluir meta semanal' });
  await confirmation.getByRole('button', { name: 'Excluir meta', exact: true }).click();
  await expect(confirmation).toBeHidden();
  await expect(panel.getByRole('alert')).toContainText('alterada por outra pessoa');
  await expect(panel.locator('.mission-weekly-progress-current dd').nth(0)).toHaveText('10 p.p.');
  await expect(panel.getByText('2 versões', { exact: true })).toHaveCount(0);
});

test('exclui meta física futura sem afetar a semana atual e mantém ações utilizáveis no celular', async ({ page }) => {
  const panel = panelFor(page);
  await panel.getByLabel('Avanço previsto para a semana (p.p.)').fill('10');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await panel.getByRole('button', { name: 'Definir meta', exact: true }).click();
  await panel.getByLabel(/^Semana\s*\*?$/).fill('2026-10-05');
  await panel.getByLabel('Medida da meta').selectOption('L');
  await panel.getByLabel('Total geral (L)').fill('1000');
  await panel.getByRole('button', { name: 'Salvar meta', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await panel.getByRole('button', { name: 'Excluir meta da semana de 05/10/2026', exact: true }).click();
  await page.getByRole('dialog', { name: 'Excluir meta semanal' }).getByRole('button', { name: 'Excluir meta', exact: true }).click();
  await expect(panel.getByRole('button', { name: 'Definir meta da semana de 05/10/2026', exact: true })).toBeVisible();
  await expect(panel.getByRole('button', { name: 'Excluir meta da semana de 05/10/2026', exact: true })).toHaveCount(0);
  await expect(panel.locator('.mission-weekly-progress-current dd').nth(0)).toHaveText('10 p.p.');
  await panel.getByText('2 versões', { exact: true }).click();
  await expect(panel.locator('.mission-weekly-progress-table details[open]')).toContainText('1.000 L');
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)).toBeLessThanOrEqual(1);
});
